import { normalizeToken } from '../utils/normalization.js';

const PERIOD_BY_SUFFIX = Object.freeze({
  B: 'Manhã',
  C: 'Tarde',
  D: 'Noite'
});

// Catálogo original do Centro-Norte. O período não fica mais duplicado
// manualmente: ele é sempre resolvido pela última letra do código da equipe.
const rawCentroNorteCatalog = [
  ['CNB-EN-90B', 'Canindé', 'Própria', 'Centro-Norte'],
  ['CND-RD-21B', 'Canindé', 'Parceira', 'Centro-Norte'],
  ['CNB-EN-91B', 'Canindé', 'Própria', 'Centro-Norte'],
  ['CND-RD-22B', 'Canindé', 'Parceira', 'Centro-Norte'],
  ['CNB-EN-92B', 'Canindé', 'Própria', 'Centro-Norte'],
  ['CND-RD-23B', 'Canindé', 'Parceira', 'Centro-Norte'],
  ['CND-EN-90B', 'Canindé', 'Própria', 'Centro-Norte'],
  ['CNM-RD-21B', 'Canindé', 'Parceira', 'Centro-Norte'],
  ['CND-EN-91B', 'Canindé', 'Própria', 'Centro-Norte'],
  ['CNB-RD-21B', 'Canindé', 'Parceira', 'Centro-Norte'],
  ['CND-EN-92B', 'Canindé', 'Própria', 'Centro-Norte'],
  ['CNI-RD-21B', 'Canindé', 'Parceira', 'Centro-Norte'],
  ['CND-EN-93B', 'Canindé', 'Própria', 'Centro-Norte'],
  ['CND-RD-21C', 'Canindé', 'Parceira', 'Centro-Norte'],
  ['CND-EN-94B', 'Canindé', 'Própria', 'Centro-Norte'],
  ['CNB-RD-21C', 'Canindé', 'Parceira', 'Centro-Norte'],
  ['CND-EN-95B', 'Canindé', 'Própria', 'Centro-Norte'],
  ['CNI-RD-21C', 'Canindé', 'Parceira', 'Centro-Norte'],
  ['CNM-RD-21D', 'Canindé', 'Parceira', 'Centro-Norte'],
  ['CND-RD-21D', 'Canindé', 'Parceira', 'Centro-Norte'],
  ['CNQ-EN-90B', 'Quixadá', 'Própria', 'Centro-Norte'],
  ['QXD-RD-21B', 'Quixadá', 'Parceira', 'Centro-Norte'],
  ['CNQ-EN-91B', 'Quixadá', 'Própria', 'Centro-Norte'],
  ['QXD-RD-22B', 'Quixadá', 'Parceira', 'Centro-Norte'],
  ['CNQ-EN-92B', 'Quixadá', 'Própria', 'Centro-Norte'],
  ['QXB-RD-21B', 'Quixadá', 'Parceira', 'Centro-Norte'],
  ['CNQ-EN-93B', 'Quixadá', 'Própria', 'Centro-Norte'],
  ['QXB-RD-22B', 'Quixadá', 'Parceira', 'Centro-Norte'],
  ['CNQ-EN-94B', 'Quixadá', 'Própria', 'Centro-Norte'],
  ['QXU-RD-21B', 'Quixadá', 'Parceira', 'Centro-Norte'],
  ['CNX-EN-90B', 'Quixadá', 'Própria', 'Centro-Norte'],
  ['QXD-RD-21C', 'Quixadá', 'Parceira', 'Centro-Norte'],
  ['CNX-EN-91B', 'Quixadá', 'Própria', 'Centro-Norte'],
  ['QXB-RD-21C', 'Quixadá', 'Parceira', 'Centro-Norte'],
  ['CNX-EN-92B', 'Quixadá', 'Própria', 'Centro-Norte'],
  ['QXB-RD-21D', 'Quixadá', 'Parceira', 'Centro-Norte'],
  ['CNX-EN-94B', 'Quixadá', 'Própria', 'Centro-Norte'],
  ['QXU-RD-21D', 'Quixadá', 'Parceira', 'Centro-Norte'],
  ['QXD-RD-23B', 'Quixadá', 'Parceira', 'Centro-Norte'],
  ['QXD-RD-21D', 'Quixadá', 'Parceira', 'Centro-Norte'],
  ['NVC-EN-90B', 'Crateús', 'Própria', 'Centro-Norte'],
  ['CAT-RD-21B', 'Crateús', 'Parceira', 'Centro-Norte'],
  ['NVC-EN-91B', 'Crateús', 'Própria', 'Centro-Norte'],
  ['CAT-RD-22B', 'Crateús', 'Parceira', 'Centro-Norte'],
  ['NVC-EN-92B', 'Crateús', 'Própria', 'Centro-Norte'],
  ['CAT-RD-21C', 'Crateús', 'Parceira', 'Centro-Norte'],
  ['NVC-EN-93B', 'Crateús', 'Própria', 'Centro-Norte'],
  ['CAT-RD-22C', 'Crateús', 'Parceira', 'Centro-Norte'],
  ['NVC-EN-94B', 'Crateús', 'Própria', 'Centro-Norte'],
  ['CAT-RD-23C', 'Crateús', 'Parceira', 'Centro-Norte'],
  ['NVC-EN-95B', 'Crateús', 'Própria', 'Centro-Norte'],
  ['CAT-RD-21D', 'Crateús', 'Parceira', 'Centro-Norte'],
  ['NVQ-EN-90B', 'Nova Russas', 'Própria', 'Centro-Norte'],
  ['NVR-RD-21B', 'Nova Russas', 'Parceira', 'Centro-Norte'],
  ['NVQ-EN-91B', 'Nova Russas', 'Própria', 'Centro-Norte'],
  ['NVR-RD-22B', 'Nova Russas', 'Parceira', 'Centro-Norte'],
  ['NVQ-EN-92B', 'Nova Russas', 'Própria', 'Centro-Norte'],
  ['NVR-RD-23B', 'Nova Russas', 'Parceira', 'Centro-Norte'],
  ['NVQ-EN-93B', 'Nova Russas', 'Própria', 'Centro-Norte'],
  ['NVI-RD-21B', 'Nova Russas', 'Parceira', 'Centro-Norte'],
  ['NVR-EN-90B', 'Nova Russas', 'Própria', 'Centro-Norte'],
  ['NVI-RD-22B', 'Nova Russas', 'Parceira', 'Centro-Norte'],
  ['NVR-EN-91B', 'Nova Russas', 'Própria', 'Centro-Norte'],
  ['NVQ-RD-21B', 'Nova Russas', 'Parceira', 'Centro-Norte'],
  ['NVR-EN-92B', 'Nova Russas', 'Própria', 'Centro-Norte'],
  ['NVM-RD-21B', 'Nova Russas', 'Parceira', 'Centro-Norte'],
  ['NVR-EN-93B', 'Nova Russas', 'Própria', 'Centro-Norte'],
  ['NVV-RD-21B', 'Nova Russas', 'Parceira', 'Centro-Norte'],
  ['NVR-EN-94B', 'Nova Russas', 'Própria', 'Centro-Norte'],
  ['NVR-RD-21C', 'Nova Russas', 'Parceira', 'Centro-Norte'],
  ['NVR-EN-95B', 'Nova Russas', 'Própria', 'Centro-Norte'],
  ['NVV-RD-21C', 'Nova Russas', 'Parceira', 'Centro-Norte'],
  ['NVV-EN-90B', 'Nova Russas', 'Própria', 'Centro-Norte'],
  ['NVI-RD-21C', 'Nova Russas', 'Parceira', 'Centro-Norte'],
  ['NVR-RD-22C', 'Nova Russas', 'Parceira', 'Centro-Norte'],
  ['NVR-RD-21D', 'Nova Russas', 'Parceira', 'Centro-Norte'],
  ['NVQ-RD-21D', 'Nova Russas', 'Parceira', 'Centro-Norte'],
];

// Equipes fornecidas na planilha Equipes_UTS.xlsx.
// Estrutura: [equipe, base, tipoEquipe, polo].
const rawUtsCatalog = [
  ['ICO-RL-01B', 'Icó', 'Parceira', 'Centro Sul'],
  ['ICO-RD-11B', 'Icó', 'Parceira', 'Centro Sul'],
  ['IGT-RL-01B', 'Iguatu', 'Parceira', 'Centro Sul'],
  ['IGT-RD-11B', 'Iguatu', 'Parceira', 'Centro Sul'],
  ['TAA-RL-01B', 'Tauá', 'Parceira', 'Centro Sul'],
  ['ICO-RD-90B', 'Icó', 'Própria', 'Centro Sul'],
  ['ICO-TR-90B', 'Icó', 'Própria', 'Centro Sul'],
  ['ICO-TR-91B', 'Icó', 'Própria', 'Centro Sul'],
  ['ICL-RD-90B', 'Icó', 'Própria', 'Centro Sul'],
  ['ICL-TR-90B', 'Icó', 'Própria', 'Centro Sul'],
  ['ICO-RD-91C', 'Icó', 'Própria', 'Centro Sul'],
  ['ICL-RD-90C', 'Icó', 'Própria', 'Centro Sul'],
  ['ICL-SK-90C', 'Icó', 'Própria', 'Centro Sul'],
  ['ICO-SK-90D', 'Icó', 'Própria', 'Centro Sul'],
  ['IGT-RD-82B', 'Iguatu', 'Própria', 'Centro Sul'],
  ['IGT-SK-93B', 'Iguatu', 'Própria', 'Centro Sul'],
  ['IGT-SK-90B', 'Iguatu', 'Própria', 'Centro Sul'],
  ['IGT-SK-91B', 'Iguatu', 'Própria', 'Centro Sul'],
  ['IGT-RD-87C', 'Iguatu', 'Própria', 'Centro Sul'],
  ['IGT-RD-88C', 'Iguatu', 'Própria', 'Centro Sul'],
  ['IGT-RD-89C', 'Iguatu', 'Própria', 'Centro Sul'],
  ['IGT-RD-90C', 'Iguatu', 'Própria', 'Centro Sul'],
  ['IGT-SK-90C', 'Iguatu', 'Própria', 'Centro Sul'],
  ['IGT-SK-91D', 'Iguatu', 'Própria', 'Centro Sul'],
  ['TAM-RD-90B', 'Senador', 'Própria', 'Centro Sul'],
  ['TAM-SK-90B', 'Senador', 'Própria', 'Centro Sul'],
  ['TAL-SK-90B', 'Senador', 'Própria', 'Centro Sul'],
  ['TAS-RD-90B', 'Senador', 'Própria', 'Centro Sul'],
  ['TAS-RD-91B', 'Senador', 'Própria', 'Centro Sul'],
  ['TAL-SK-90C', 'Senador', 'Própria', 'Centro Sul'],
  ['TAS-RD-91C', 'Senador', 'Própria', 'Centro Sul'],
  ['TAS-RD-93C', 'Senador', 'Própria', 'Centro Sul'],
  ['TAS-RD-90D', 'Senador', 'Própria', 'Centro Sul'],
  ['TAA-RD-90B', 'Tauá', 'Própria', 'Centro Sul'],
  ['TAA-RD-91B', 'Tauá', 'Própria', 'Centro Sul'],
  ['TAP-RD-91B', 'Tauá', 'Própria', 'Centro Sul'],
  ['TAP-RD-90B', 'Tauá', 'Própria', 'Centro Sul'],
  ['TAP-RD-90C', 'Tauá', 'Própria', 'Centro Sul'],
  ['TAA-RD-90C', 'Tauá', 'Própria', 'Centro Sul'],
  ['TAA-RD-91C', 'Tauá', 'Própria', 'Centro Sul'],
  ['TAA-RD-90D', 'Tauá', 'Própria', 'Centro Sul'],
  ['ARI-RD-11B', 'Aracati', 'Parceira', 'Leste'],
  ['ARJ-RD-11B', 'Aracati', 'Parceira', 'Leste'],
  ['ART-RD-11B', 'Aracati', 'Parceira', 'Leste'],
  ['ART-RD-13B', 'Aracati', 'Parceira', 'Leste'],
  ['JGB-RD-12B', 'Jaguaribe', 'Parceira', 'Leste'],
  ['JGI-RD-11B', 'Jaguaribe', 'Parceira', 'Leste'],
  ['RSL-SK-11B', 'Russas', 'Parceira', 'Leste'],
  ['RSM-RD-11B', 'Russas', 'Parceira', 'Leste'],
  ['RSU-RD-12B', 'Russas', 'Parceira', 'Leste'],
  ['ART-RD-11C', 'Aracati', 'Parceira', 'Leste'],
  ['ART-RD-16C', 'Aracati', 'Parceira', 'Leste'],
  ['RSL-SK-11C', 'Russas', 'Parceira', 'Leste'],
  ['RSM-RD-11C', 'Russas', 'Parceira', 'Leste'],
  ['RSU-RD-11C', 'Russas', 'Parceira', 'Leste'],
  ['ARI-RD-11D', 'Aracati', 'Parceira', 'Leste'],
  ['ART-RD-12D', 'Aracati', 'Parceira', 'Leste'],
  ['JGB-RD-12D', 'Jaguaribe', 'Parceira', 'Leste'],
  ['RSL-RD-14D', 'Russas', 'Parceira', 'Leste'],
  ['ARI-SK-90B', 'Aracati', 'Própria', 'Leste'],
  ['ART-RD-90B', 'Aracati', 'Própria', 'Leste'],
  ['ART-SK-90B', 'Aracati', 'Própria', 'Leste'],
  ['JGB-RD-90B', 'Jaguaribe', 'Própria', 'Leste'],
  ['JGI-SK-90B', 'Jaguaribe', 'Própria', 'Leste'],
  ['JGR-SK-90B', 'Jaguaribe', 'Própria', 'Leste'],
  ['RSL-SK-90B', 'Russas', 'Própria', 'Leste'],
  ['RSM-SK-90B', 'Russas', 'Própria', 'Leste'],
  ['RSU-RD-91B', 'Russas', 'Própria', 'Leste'],
  ['RSU-SK-90B', 'Russas', 'Própria', 'Leste'],
  ['ARI-SK-90C', 'Aracati', 'Própria', 'Leste'],
  ['ARJ-SK-90C', 'Aracati', 'Própria', 'Leste'],
  ['ART-SK-90C', 'Aracati', 'Própria', 'Leste'],
  ['JGB-SK-90C', 'Jaguaribe', 'Própria', 'Leste'],
  ['JGI-RD-90C', 'Jaguaribe', 'Própria', 'Leste'],
  ['JGR-RD-90C', 'Jaguaribe', 'Própria', 'Leste'],
  ['RSL-SK-90C', 'Russas', 'Própria', 'Leste'],
  ['RSM-RD-90C', 'Russas', 'Própria', 'Leste'],
  ['RSU-RD-91C', 'Russas', 'Própria', 'Leste'],
  ['RSU-SK-90C', 'Russas', 'Própria', 'Leste'],
  ['ART-RD-90D', 'Aracati', 'Própria', 'Leste'],
  ['ART-SK-90D', 'Aracati', 'Própria', 'Leste'],
  ['JGB-RD-90D', 'Jaguaribe', 'Própria', 'Leste'],
  ['CPE-RD-16B', 'Campos Sales', 'Parceira', 'Sul'],
  ['CPF-RD-14B', 'Campos Sales', 'Parceira', 'Sul'],
  ['CPN-EN-01B', 'Campos Sales', 'Parceira', 'Sul'],
  ['CPN-RD-90B', 'Campos Sales', 'Parceira', 'Sul'],
  ['CPS-EN-02B', 'Campos Sales', 'Parceira', 'Sul'],
  ['CPS-TR-11B', 'Campos Sales', 'Parceira', 'Sul'],
  ['JZB-EN-01B', 'Juazeiro do Norte', 'Parceira', 'Sul'],
  ['JZB-RD-16B', 'Juazeiro do Norte', 'Parceira', 'Sul'],
  ['JZC-EN-01B', 'Juazeiro do Norte', 'Parceira', 'Sul'],
  ['JZC-RD-17B', 'Juazeiro do Norte', 'Parceira', 'Sul'],
  ['JZC-RD-18B', 'Juazeiro do Norte', 'Parceira', 'Sul'],
  ['JZN-RD-10B', 'Juazeiro do Norte', 'Parceira', 'Sul'],
  ['JZN-RD-11B', 'Juazeiro do Norte', 'Parceira', 'Sul'],
  ['JZN-RD-15B', 'Juazeiro do Norte', 'Parceira', 'Sul'],
  ['JZN-RD-28B', 'Juazeiro do Norte', 'Parceira', 'Sul'],
  ['JZN-SK-11B', 'Juazeiro do Norte', 'Parceira', 'Sul'],
  ['JZU-RD-14B', 'Juazeiro do Norte', 'Parceira', 'Sul'],
  ['MLB-EN-01B', 'Milagres', 'Parceira', 'Sul'],
  ['MLB-RD-13B', 'Milagres', 'Parceira', 'Sul'],
  ['MLG-TR-11B', 'Milagres', 'Parceira', 'Sul'],
  ['MLJ-RD-17B', 'Milagres', 'Parceira', 'Sul'],
  ['MLM-EN-01B', 'Milagres', 'Parceira', 'Sul'],
  ['MLM-RD-16B', 'Milagres', 'Parceira', 'Sul'],
  ['MLS-RD-15B', 'Milagres', 'Parceira', 'Sul'],
  ['MLV-RD-12B', 'Milagres', 'Parceira', 'Sul'],
  ['CPE-RD-12C', 'Campos Sales', 'Parceira', 'Sul'],
  ['CPS-TR-11C', 'Campos Sales', 'Parceira', 'Sul'],
  ['JZC-RD-12C', 'Juazeiro do Norte', 'Parceira', 'Sul'],
  ['JZN-RD-10C', 'Juazeiro do Norte', 'Parceira', 'Sul'],
  ['JZN-RD-16C', 'Juazeiro do Norte', 'Parceira', 'Sul'],
  ['JZN-RD-17C', 'Juazeiro do Norte', 'Parceira', 'Sul'],
  ['JZN-RD-19C', 'Juazeiro do Norte', 'Parceira', 'Sul'],
  ['JZN-SK-11C', 'Juazeiro do Norte', 'Parceira', 'Sul'],
  ['MLB-RD-13C', 'Milagres', 'Parceira', 'Sul'],
  ['MLM-RD-14C', 'Milagres', 'Parceira', 'Sul'],
  ['MLS-RD-12C', 'Milagres', 'Parceira', 'Sul'],
  ['CPA-RD-13D', 'Campos Sales', 'Parceira', 'Sul'],
  ['CPN-RD-12D', 'Campos Sales', 'Parceira', 'Sul'],
  ['JZC-RD-14D', 'Juazeiro do Norte', 'Parceira', 'Sul'],
  ['JZN-RD-13D', 'Juazeiro do Norte', 'Parceira', 'Sul'],
  ['JZN-RD-15D', 'Juazeiro do Norte', 'Parceira', 'Sul'],
  ['CPA-RD-90B', 'Campos Sales', 'Própria', 'Sul'],
  ['CPS-RD-90B', 'Campos Sales', 'Própria', 'Sul'],
  ['JZN-RD-90B', 'Juazeiro do Norte', 'Própria', 'Sul'],
  ['JZN-RD-91B', 'Juazeiro do Norte', 'Própria', 'Sul'],
  ['JZN-RD-92B', 'Juazeiro do Norte', 'Própria', 'Sul'],
  ['MLB-RD-90B', 'Milagres', 'Própria', 'Sul'],
  ['MLG-RD-90B', 'Milagres', 'Própria', 'Sul'],
  ['MLM-RD-90B', 'Milagres', 'Própria', 'Sul'],
  ['MLS-RD-90B', 'Milagres', 'Própria', 'Sul'],
  ['MLS-RD-90C', 'Milagres', 'Própria', 'Sul'],
];

// Exceções de equipes que anteriormente caíam na Base/Regional genérica
// informada pelo arquivo principal.
const rawRegionalOverrides = [
  ['SBA-RD-01B', 'Sobral', 'Parceira', 'Norte'],
  ['SBA-RD-02B', 'Sobral', 'Parceira', 'Norte'],
  ['ACU-AP-01B', 'Acaraú', 'Própria', 'Atlântico'],
  ['ACU-AP-01D', 'Acaraú', 'Própria', 'Atlântico'],
  ['ACU-AP-31D', 'Acaraú', 'Própria', 'Atlântico'],
  ['ITP-RD-01B', 'Itapipoca', 'Parceira', 'Atlântico'],
  ['TRI-RD-01B', 'Trairi', 'Parceira', 'Atlântico'],
  ['TRI-RD-03C', 'Trairi', 'Parceira', 'Atlântico'],
  ['TRI-RD-21D', 'Trairi', 'Parceira', 'Atlântico'],
  ['TRI-RD-23B', 'Trairi', 'Parceira', 'Atlântico'],
  ['TRI-RD-31B', 'Trairi', 'Parceira', 'Atlântico'],
  ['TRI-RD-32C', 'Trairi', 'Parceira', 'Atlântico'],

  // Centro Sul: equipes que chegavam com a Base genérica "Centro Sul".
  ['ICL-RD-90D', 'Icó', 'Própria', 'Centro Sul'],
  ['ICL-SK-90B', 'Icó', 'Própria', 'Centro Sul'],
  ['ICL-SK-90D', 'Icó', 'Própria', 'Centro Sul'],
  ['ICO-RD-90C', 'Icó', 'Própria', 'Centro Sul'],
  ['ICO-RD-90D', 'Icó', 'Própria', 'Centro Sul'],
  ['ICO-SK-90B', 'Icó', 'Própria', 'Centro Sul'],
  ['ICO-TR-90C', 'Icó', 'Própria', 'Centro Sul'],
  ['IGT-RD-81B', 'Iguatu', 'Própria', 'Centro Sul'],
  ['IGT-RD-84B', 'Iguatu', 'Própria', 'Centro Sul'],
  ['IGT-RD-91D', 'Iguatu', 'Própria', 'Centro Sul'],
  ['TAA-TR-90D', 'Tauá', 'Própria', 'Centro Sul'],
  ['TAL-EN-01C', 'Senador', 'Parceira', 'Centro Sul'],
  ['TAM-EN-01C', 'Senador', 'Parceira', 'Centro Sul'],
  ['TAM-RD-90C', 'Senador', 'Própria', 'Centro Sul'],
  ['TAS-RD-92B', 'Senador', 'Própria', 'Centro Sul'],
  ['TAS-RD-93B', 'Senador', 'Própria', 'Centro Sul'],
  ['TAS-RD-94B', 'Senador', 'Própria', 'Centro Sul'],

  // Sul: complementos informados manualmente com o tipo de equipe
  // definido explicitamente conforme a classificação operacional fornecida.
  // Campos Sales
  ['CPA-EN-01B', 'Campos Sales', 'Parceira', 'Sul'],
  ['CPB-RD-15B', 'Campos Sales', 'Parceira', 'Sul'],
  ['CPN-RD-13B', 'Campos Sales', 'Parceira', 'Sul'],
  ['CPN-RD-13C', 'Campos Sales', 'Parceira', 'Sul'],
  ['CPR-RD-12B', 'Campos Sales', 'Parceira', 'Sul'],
  ['CPR-RD-14D', 'Campos Sales', 'Parceira', 'Sul'],
  ['CPS-RD-11C', 'Campos Sales', 'Parceira', 'Sul'],
  // Juazeiro
  ['JZB-RD-16C', 'Juazeiro', 'Parceira', 'Sul'],
  ['JZC-RD-90C', 'Juazeiro', 'Própria', 'Sul'],
  ['JZN-EN-02B', 'Juazeiro', 'Parceira', 'Sul'],
  ['JZN-RD-22B', 'Juazeiro', 'Parceira', 'Sul'],
  ['JZN-RD-25B', 'Juazeiro', 'Parceira', 'Sul'],
  ['JZN-RD-27B', 'Juazeiro', 'Parceira', 'Sul'],
  ['JZN-RD-90C', 'Juazeiro', 'Própria', 'Sul'],
  ['JZN-RD-91C', 'Juazeiro', 'Própria', 'Sul'],
  ['JZN-RD-92C', 'Juazeiro', 'Própria', 'Sul'],
  ['JZN-RD-93B', 'Juazeiro', 'Própria', 'Sul'],
  ['JZN-RD-93C', 'Juazeiro', 'Própria', 'Sul'],
  // Milagres
  ['MLB-EN-01C', 'Milagres', 'Parceira', 'Sul'],
  ['MLB-RD-15D', 'Milagres', 'Parceira', 'Sul'],
  ['MLG-EN-01B', 'Milagres', 'Parceira', 'Sul'],
  ['MLG-RD-14B', 'Milagres', 'Parceira', 'Sul'],
  ['MLG-RD-15B', 'Milagres', 'Parceira', 'Sul'],
  ['MLG-RD-90C', 'Milagres', 'Própria', 'Sul'],
  ['MLG-RD-91B', 'Milagres', 'Própria', 'Sul'],
  ['MLG-TR-11C', 'Milagres', 'Parceira', 'Sul'],
  ['MLM-EN-01C', 'Milagres', 'Parceira', 'Sul'],
  ['MLP-RD-18B', 'Milagres', 'Parceira', 'Sul'],
  ['MLS-EN-01B', 'Milagres', 'Parceira', 'Sul'],
  ['MLS-RD-91B', 'Milagres', 'Própria', 'Sul'],
  ['MLV-RD-16C', 'Milagres', 'Parceira', 'Sul'],

  // Leste: complementos informados manualmente com o tipo de equipe
  // definido explicitamente conforme a classificação operacional fornecida.
  // Aracati
  ['ARI-RD-11C', 'Aracati', 'Parceira', 'Leste'],
  ['ARI-RD-12B', 'Aracati', 'Parceira', 'Leste'],
  ['ARI-RD-12D', 'Aracati', 'Parceira', 'Leste'],
  ['ARI-RD-90B', 'Aracati', 'Própria', 'Leste'],
  ['ARI-RD-90C', 'Aracati', 'Própria', 'Leste'],
  ['ARJ-RD-11C', 'Aracati', 'Parceira', 'Leste'],
  ['ARJ-RD-90C', 'Aracati', 'Própria', 'Leste'],
  ['ART-RD-12B', 'Aracati', 'Parceira', 'Leste'],
  ['ART-RD-13C', 'Aracati', 'Parceira', 'Leste'],
  ['ART-RD-14B', 'Aracati', 'Parceira', 'Leste'],
  ['ART-RD-14C', 'Aracati', 'Parceira', 'Leste'],
  ['ART-RD-15B', 'Aracati', 'Parceira', 'Leste'],
  ['ART-RD-15C', 'Aracati', 'Parceira', 'Leste'],
  ['ART-RD-50B', 'Aracati', 'Parceira', 'Leste'],
  ['ART-RD-50D', 'Aracati', 'Parceira', 'Leste'],
  ['ART-RD-51B', 'Aracati', 'Parceira', 'Leste'],
  ['ART-RD-51D', 'Aracati', 'Parceira', 'Leste'],
  ['ART-RD-56B', 'Aracati', 'Parceira', 'Leste'],
  ['ART-RD-56C', 'Aracati', 'Parceira', 'Leste'],
  ['ART-RD-57B', 'Aracati', 'Parceira', 'Leste'],
  ['ART-RD-57C', 'Aracati', 'Parceira', 'Leste'],
  ['ART-RD-90C', 'Aracati', 'Parceira', 'Leste'],
  ['ART-RL-03B', 'Aracati', 'Parceira', 'Leste'],
  ['ART-RL-04B', 'Aracati', 'Parceira', 'Leste'],
  ['ART-RL-05B', 'Aracati', 'Parceira', 'Leste'],
  ['ART-RL-07B', 'Aracati', 'Parceira', 'Leste'],
  // Jaguaribe
  ['JGB-EN-01B', 'Jaguaribe', 'Parceira', 'Leste'],
  ['JGB-RD-11B', 'Jaguaribe', 'Parceira', 'Leste'],
  ['JGB-RD-11C', 'Jaguaribe', 'Parceira', 'Leste'],
  ['JGB-RD-50B', 'Jaguaribe', 'Parceira', 'Leste'],
  ['JGB-RD-90C', 'Jaguaribe', 'Própria', 'Leste'],
  ['JGB-SK-90B', 'Jaguaribe', 'Própria', 'Leste'],
  ['JGI-RD-11C', 'Jaguaribe', 'Parceira', 'Leste'],
  ['JGI-RD-12D', 'Jaguaribe', 'Parceira', 'Leste'],
  ['JGI-RD-90B', 'Jaguaribe', 'Própria', 'Leste'],
  ['JGI-RD-91B', 'Jaguaribe', 'Própria', 'Leste'],
  ['JGR-RD-11B', 'Jaguaribe', 'Parceira', 'Leste'],
  ['JGR-RD-11C', 'Jaguaribe', 'Parceira', 'Leste'],
  ['JGR-RD-90B', 'Jaguaribe', 'Própria', 'Leste'],
  // Russas
  ['RSL-EN-01B', 'Russas', 'Parceira', 'Leste'],
  ['RSL-RD-11B', 'Russas', 'Parceira', 'Leste'],
  ['RSL-RD-11C', 'Russas', 'Parceira', 'Leste'],
  ['RSL-RD-12B', 'Russas', 'Parceira', 'Leste'],
  ['RSL-RD-12C', 'Russas', 'Parceira', 'Leste'],
  ['RSL-RD-14B', 'Russas', 'Parceira', 'Leste'],
  ['RSL-RD-14C', 'Russas', 'Parceira', 'Leste'],
  ['RSL-RD-90B', 'Russas', 'Própria', 'Leste'],
  ['RSL-RD-90C', 'Russas', 'Própria', 'Leste'],
  ['RSL-RD-90D', 'Russas', 'Própria', 'Leste'],
  ['RSM-RD-12B', 'Russas', 'Parceira', 'Leste'],
  ['RSM-RD-12D', 'Russas', 'Parceira', 'Leste'],
  ['RSM-RD-90B', 'Russas', 'Própria', 'Leste'],
  ['RSU-EN-02B', 'Russas', 'Parceira', 'Leste'],
  ['RSU-RD-11B', 'Russas', 'Parceira', 'Leste'],
  ['RSU-RD-12C', 'Russas', 'Parceira', 'Leste'],
  ['RSU-RD-90B', 'Russas', 'Própria', 'Leste'],
  ['RSU-RD-90C', 'Russas', 'Própria', 'Leste'],
  ['RSU-RD-90D', 'Russas', 'Própria', 'Leste'],
];

const rawTeamCatalog = [
  ...rawCentroNorteCatalog,
  ...rawUtsCatalog,
  ...rawRegionalOverrides
];

// Consolida entradas duplicadas por equipe. Correções posteriores podem trocar
// base/polo sem apagar um tipo de equipe já conhecido no catálogo anterior.
const mergedTeamCatalog = new Map();

for (const [equipe, base, tipoEquipe, polo] of rawTeamCatalog) {
  const key = normalizeToken(equipe);
  if (!key) continue;

  const current = mergedTeamCatalog.get(key);
  mergedTeamCatalog.set(key, {
    equipe: String(equipe || '').trim(),
    base: canonicalBase(base || current?.base || ''),
    periodo: resolveTeamPeriod(equipe, current?.periodo || ''),
    tipoEquipe: String(tipoEquipe || current?.tipoEquipe || '').trim(),
    polo: String(polo || current?.polo || '').trim()
  });
}

export const VTR_TEAM_CATALOG = [...mergedTeamCatalog.values()];

export const VTR_TEAM_INDEX = new Map(
  VTR_TEAM_CATALOG.map((entry) => [normalizeToken(entry.equipe), entry])
);

// Regra única solicitada:
// B = Manhã, C = Tarde e D = Noite.
// O fallback só é usado quando o código não termina em B, C ou D.
export function resolveTeamPeriod(teamName, fallback = '') {
  const code = String(teamName || '').trim().toUpperCase();
  const suffix = code.slice(-1);
  return PERIOD_BY_SUFFIX[suffix] || String(fallback || '').trim();
}

export function canonicalBase(base) {
  const token = normalizeToken(base);
  const canonical = new Map([
    ['CANINDE', 'Canindé'],
    ['QUIXADA', 'Quixadá'],
    ['CRATEUS', 'Crateús'],
    ['NOVARUSSAS', 'Nova Russas'],
    ['INHUCU', 'Inhuçu'],
    ['TIANGUA', 'Tianguá'],
    ['CAMOCIM', 'Camocim'],
    ['SOBRAL', 'Sobral'],
    ['ITAPAJE', 'Itapajé'],
    ['ITAPIPOCA', 'Itapipoca'],
    ['TRAIRI', 'Trairi'],
    ['ACARAU', 'Acaraú'],
    ['ICO', 'Icó'],
    ['IGUATU', 'Iguatu'],
    ['SENADOR', 'Senador'],
    ['TAUA', 'Tauá'],
    ['ARACATI', 'Aracati'],
    ['JAGUARIBE', 'Jaguaribe'],
    ['RUSSAS', 'Russas'],
    ['CAMPOSSALES', 'Campos Sales'],
    ['JUAZEIRODONORTE', 'Juazeiro'],
    ['JUAZEIRO', 'Juazeiro'],
    ['MILAGRES', 'Milagres']
  ]);
  return canonical.get(token) || String(base || '').trim();
}
