import { normalizeToken } from '../utils/normalization.js';

const PERIOD_BY_SUFFIX = Object.freeze({
  B: 'Manhã',
  C: 'Tarde',
  D: 'Noite'
});

const BASE_BY_TOKEN = new Map([
  ["CANINDE", "Canindé"],
  ["QUIXADA", "Quixadá"],
  ["CRATEUS", "Crateús"],
  ["NOVARUSSAS", "Nova Russas"],
  ["INHUCU", "Inhuçu"],
  ["TIANGUA", "Tianguá"],
  ["CAMOCIM", "Camocim"],
  ["SOBRAL", "Sobral"],
  ["ITAPAJE", "Itapajé"],
  ["ITAPIPOCA", "Itapipoca"],
  ["TRAIRI", "Trairi"],
  ["ACARAU", "Acaraú"],
  ["ICO", "Icó"],
  ["IGUATU", "Iguatu"],
  ["SENADOR", "Senador"],
  ["TAUA", "Tauá"],
  ["ARACATI", "Aracati"],
  ["JAGUARIBE", "Jaguaribe"],
  ["RUSSAS", "Russas"],
  ["CAMPOSSALES", "Campos Sales"],
  ["JUAZEIRODONORTE", "Juazeiro do Norte"],
  ["JUAZEIRO", "Juazeiro"],
  ["MILAGRES", "Milagres"],
]);

const POLO_BY_TOKEN = new Map([
  ["CENTROSUL", "Centro Sul"],
  ["LESTE", "Leste"],
  ["SUL", "Sul"],
  ["ATLANTICO", "Atlântico"],
  ["NORTE", "Norte"],
  ["CENTRONORTE", "Centro-Norte"],
]);

const TEAM_TYPE_BY_TOKEN = new Map([
  ['PROPRIA', 'Própria'],
  ['PARCEIRA', 'Parceira']
]);

// Catálogo integral reconstruído a partir da planilha Equipes_UTS(2).xlsx.
// As equipes anteriores foram removidas. Cada aba da planilha define a regional,
// e cada linha define Base, Tipo de Equipe e Equipe.
// Total de linhas válidas: 596; total de equipes únicas: 595.
// A duplicidade idêntica CAT-RD-21B da aba Centro Norte foi consolidada uma única vez.
const RAW_TEAM_CATALOG = [
  // Centro Sul: 41 equipes
  // Base: Icó
  ["ICO-RL-01B", "Icó", "Parceira", "Centro Sul"],
  ["ICO-RD-11B", "Icó", "Parceira", "Centro Sul"],
  // Base: Iguatu
  ["IGT-RL-01B", "Iguatu", "Parceira", "Centro Sul"],
  ["IGT-RD-11B", "Iguatu", "Parceira", "Centro Sul"],
  // Base: Tauá
  ["TAA-RL-01B", "Tauá", "Parceira", "Centro Sul"],
  // Base: Icó
  ["ICO-RD-90B", "Icó", "Própria", "Centro Sul"],
  ["ICO-TR-90B", "Icó", "Própria", "Centro Sul"],
  ["ICO-TR-91B", "Icó", "Própria", "Centro Sul"],
  ["ICL-RD-90B", "Icó", "Própria", "Centro Sul"],
  ["ICL-TR-90B", "Icó", "Própria", "Centro Sul"],
  ["ICO-RD-91C", "Icó", "Própria", "Centro Sul"],
  ["ICL-RD-90C", "Icó", "Própria", "Centro Sul"],
  ["ICL-SK-90C", "Icó", "Própria", "Centro Sul"],
  ["ICO-SK-90D", "Icó", "Própria", "Centro Sul"],
  // Base: Iguatu
  ["IGT-RD-82B", "Iguatu", "Própria", "Centro Sul"],
  ["IGT-SK-93B", "Iguatu", "Própria", "Centro Sul"],
  ["IGT-SK-90B", "Iguatu", "Própria", "Centro Sul"],
  ["IGT-SK-91B", "Iguatu", "Própria", "Centro Sul"],
  ["IGT-RD-87C", "Iguatu", "Própria", "Centro Sul"],
  ["IGT-RD-88C", "Iguatu", "Própria", "Centro Sul"],
  ["IGT-RD-89C", "Iguatu", "Própria", "Centro Sul"],
  ["IGT-RD-90C", "Iguatu", "Própria", "Centro Sul"],
  ["IGT-SK-90C", "Iguatu", "Própria", "Centro Sul"],
  ["IGT-SK-91D", "Iguatu", "Própria", "Centro Sul"],
  // Base: Senador
  ["TAM-RD-90B", "Senador", "Própria", "Centro Sul"],
  ["TAM-SK-90B", "Senador", "Própria", "Centro Sul"],
  ["TAL-SK-90B", "Senador", "Própria", "Centro Sul"],
  ["TAS-RD-90B", "Senador", "Própria", "Centro Sul"],
  ["TAS-RD-91B", "Senador", "Própria", "Centro Sul"],
  ["TAL-SK-90C", "Senador", "Própria", "Centro Sul"],
  ["TAS-RD-91C", "Senador", "Própria", "Centro Sul"],
  ["TAS-RD-93C", "Senador", "Própria", "Centro Sul"],
  ["TAS-RD-90D", "Senador", "Própria", "Centro Sul"],
  // Base: Tauá
  ["TAA-RD-90B", "Tauá", "Própria", "Centro Sul"],
  ["TAA-RD-91B", "Tauá", "Própria", "Centro Sul"],
  ["TAP-RD-91B", "Tauá", "Própria", "Centro Sul"],
  ["TAP-RD-90B", "Tauá", "Própria", "Centro Sul"],
  ["TAP-RD-90C", "Tauá", "Própria", "Centro Sul"],
  ["TAA-RD-90C", "Tauá", "Própria", "Centro Sul"],
  ["TAA-RD-91C", "Tauá", "Própria", "Centro Sul"],
  ["TAA-RD-90D", "Tauá", "Própria", "Centro Sul"],
  // Leste: 41 equipes
  // Base: Aracati
  ["ARI-RD-11B", "Aracati", "Parceira", "Leste"],
  ["ARJ-RD-11B", "Aracati", "Parceira", "Leste"],
  ["ART-RD-11B", "Aracati", "Parceira", "Leste"],
  ["ART-RD-13B", "Aracati", "Parceira", "Leste"],
  // Base: Jaguaribe
  ["JGB-RD-12B", "Jaguaribe", "Parceira", "Leste"],
  ["JGI-RD-11B", "Jaguaribe", "Parceira", "Leste"],
  // Base: Russas
  ["RSL-SK-11B", "Russas", "Parceira", "Leste"],
  ["RSM-RD-11B", "Russas", "Parceira", "Leste"],
  ["RSU-RD-12B", "Russas", "Parceira", "Leste"],
  // Base: Aracati
  ["ART-RD-11C", "Aracati", "Parceira", "Leste"],
  ["ART-RD-16C", "Aracati", "Parceira", "Leste"],
  // Base: Russas
  ["RSL-SK-11C", "Russas", "Parceira", "Leste"],
  ["RSM-RD-11C", "Russas", "Parceira", "Leste"],
  ["RSU-RD-11C", "Russas", "Parceira", "Leste"],
  // Base: Aracati
  ["ARI-RD-11D", "Aracati", "Parceira", "Leste"],
  ["ART-RD-12D", "Aracati", "Parceira", "Leste"],
  // Base: Jaguaribe
  ["JGB-RD-12D", "Jaguaribe", "Parceira", "Leste"],
  // Base: Russas
  ["RSL-RD-14D", "Russas", "Parceira", "Leste"],
  // Base: Aracati
  ["ARI-SK-90B", "Aracati", "Própria", "Leste"],
  ["ART-RD-90B", "Aracati", "Própria", "Leste"],
  ["ART-SK-90B", "Aracati", "Própria", "Leste"],
  // Base: Jaguaribe
  ["JGB-RD-90B", "Jaguaribe", "Própria", "Leste"],
  ["JGI-SK-90B", "Jaguaribe", "Própria", "Leste"],
  ["JGR-SK-90B", "Jaguaribe", "Própria", "Leste"],
  // Base: Russas
  ["RSL-SK-90B", "Russas", "Própria", "Leste"],
  ["RSM-SK-90B", "Russas", "Própria", "Leste"],
  ["RSU-RD-91B", "Russas", "Própria", "Leste"],
  ["RSU-SK-90B", "Russas", "Própria", "Leste"],
  // Base: Aracati
  ["ARI-SK-90C", "Aracati", "Própria", "Leste"],
  ["ARJ-SK-90C", "Aracati", "Própria", "Leste"],
  ["ART-SK-90C", "Aracati", "Própria", "Leste"],
  // Base: Jaguaribe
  ["JGB-SK-90C", "Jaguaribe", "Própria", "Leste"],
  ["JGI-RD-90C", "Jaguaribe", "Própria", "Leste"],
  ["JGR-RD-90C", "Jaguaribe", "Própria", "Leste"],
  // Base: Russas
  ["RSL-SK-90C", "Russas", "Própria", "Leste"],
  ["RSM-RD-90C", "Russas", "Própria", "Leste"],
  ["RSU-RD-91C", "Russas", "Própria", "Leste"],
  ["RSU-SK-90C", "Russas", "Própria", "Leste"],
  // Base: Aracati
  ["ART-RD-90D", "Aracati", "Própria", "Leste"],
  ["ART-SK-90D", "Aracati", "Própria", "Leste"],
  // Base: Jaguaribe
  ["JGB-RD-90D", "Jaguaribe", "Própria", "Leste"],
  // Sul: 51 equipes
  // Base: Campos Sales
  ["CPE-RD-16B", "Campos Sales", "Parceira", "Sul"],
  ["CPF-RD-14B", "Campos Sales", "Parceira", "Sul"],
  ["CPN-EN-01B", "Campos Sales", "Parceira", "Sul"],
  ["CPN-RD-90B", "Campos Sales", "Parceira", "Sul"],
  ["CPS-EN-02B", "Campos Sales", "Parceira", "Sul"],
  ["CPS-TR-11B", "Campos Sales", "Parceira", "Sul"],
  // Base: Juazeiro do Norte
  ["JZB-EN-01B", "Juazeiro do Norte", "Parceira", "Sul"],
  ["JZB-RD-16B", "Juazeiro do Norte", "Parceira", "Sul"],
  ["JZC-EN-01B", "Juazeiro do Norte", "Parceira", "Sul"],
  ["JZC-RD-17B", "Juazeiro do Norte", "Parceira", "Sul"],
  ["JZC-RD-18B", "Juazeiro do Norte", "Parceira", "Sul"],
  ["JZN-RD-10B", "Juazeiro do Norte", "Parceira", "Sul"],
  ["JZN-RD-11B", "Juazeiro do Norte", "Parceira", "Sul"],
  ["JZN-RD-15B", "Juazeiro do Norte", "Parceira", "Sul"],
  ["JZN-RD-28B", "Juazeiro do Norte", "Parceira", "Sul"],
  ["JZN-SK-11B", "Juazeiro do Norte", "Parceira", "Sul"],
  ["JZU-RD-14B", "Juazeiro do Norte", "Parceira", "Sul"],
  // Base: Milagres
  ["MLB-EN-01B", "Milagres", "Parceira", "Sul"],
  ["MLB-RD-13B", "Milagres", "Parceira", "Sul"],
  ["MLG-TR-11B", "Milagres", "Parceira", "Sul"],
  ["MLJ-RD-17B", "Milagres", "Parceira", "Sul"],
  ["MLM-EN-01B", "Milagres", "Parceira", "Sul"],
  ["MLM-RD-16B", "Milagres", "Parceira", "Sul"],
  ["MLS-RD-15B", "Milagres", "Parceira", "Sul"],
  ["MLV-RD-12B", "Milagres", "Parceira", "Sul"],
  // Base: Campos Sales
  ["CPE-RD-12C", "Campos Sales", "Parceira", "Sul"],
  ["CPS-TR-11C", "Campos Sales", "Parceira", "Sul"],
  // Base: Juazeiro do Norte
  ["JZC-RD-12C", "Juazeiro do Norte", "Parceira", "Sul"],
  ["JZN-RD-10C", "Juazeiro do Norte", "Parceira", "Sul"],
  ["JZN-RD-16C", "Juazeiro do Norte", "Parceira", "Sul"],
  ["JZN-RD-17C", "Juazeiro do Norte", "Parceira", "Sul"],
  ["JZN-RD-19C", "Juazeiro do Norte", "Parceira", "Sul"],
  ["JZN-SK-11C", "Juazeiro do Norte", "Parceira", "Sul"],
  // Base: Milagres
  ["MLB-RD-13C", "Milagres", "Parceira", "Sul"],
  ["MLM-RD-14C", "Milagres", "Parceira", "Sul"],
  ["MLS-RD-12C", "Milagres", "Parceira", "Sul"],
  // Base: Campos Sales
  ["CPA-RD-13D", "Campos Sales", "Parceira", "Sul"],
  ["CPN-RD-12D", "Campos Sales", "Parceira", "Sul"],
  // Base: Juazeiro do Norte
  ["JZC-RD-14D", "Juazeiro do Norte", "Parceira", "Sul"],
  ["JZN-RD-13D", "Juazeiro do Norte", "Parceira", "Sul"],
  ["JZN-RD-15D", "Juazeiro do Norte", "Parceira", "Sul"],
  // Base: Campos Sales
  ["CPA-RD-90B", "Campos Sales", "Própria", "Sul"],
  ["CPS-RD-90B", "Campos Sales", "Própria", "Sul"],
  // Base: Juazeiro do Norte
  ["JZN-RD-90B", "Juazeiro do Norte", "Própria", "Sul"],
  ["JZN-RD-91B", "Juazeiro do Norte", "Própria", "Sul"],
  ["JZN-RD-92B", "Juazeiro do Norte", "Própria", "Sul"],
  // Base: Milagres
  ["MLB-RD-90B", "Milagres", "Própria", "Sul"],
  ["MLG-RD-90B", "Milagres", "Própria", "Sul"],
  ["MLM-RD-90B", "Milagres", "Própria", "Sul"],
  ["MLS-RD-90B", "Milagres", "Própria", "Sul"],
  ["MLS-RD-90C", "Milagres", "Própria", "Sul"],
  // Atlântico: 153 equipes
  // Base: Acaraú
  ["ACA-CO-10B", "Acaraú", "Parceira", "Atlântico"],
  ["ACA-CO-20B", "Acaraú", "Parceira", "Atlântico"],
  ["ACA-CO-21B", "Acaraú", "Parceira", "Atlântico"],
  // Base: Itapajé
  ["ITE-CO-10B", "Itapajé", "Parceira", "Atlântico"],
  ["ITE-CO-11B", "Itapajé", "Parceira", "Atlântico"],
  ["ITE-RD-10B", "Itapajé", "Parceira", "Atlântico"],
  // Base: Itapipoca
  ["IPK-CO-10B", "Itapipoca", "Parceira", "Atlântico"],
  ["IPK-CO-11B", "Itapipoca", "Parceira", "Atlântico"],
  ["IPK-CO-12B", "Itapipoca", "Parceira", "Atlântico"],
  ["IPK-RD-10B", "Itapipoca", "Parceira", "Atlântico"],
  // Base: Acaraú
  ["ACA-RD-01B", "Acaraú", "Parceira", "Atlântico"],
  ["ACA-RD-02B", "Acaraú", "Parceira", "Atlântico"],
  ["ACA-RD-03D", "Acaraú", "Parceira", "Atlântico"],
  ["ACA-RD-05C", "Acaraú", "Parceira", "Atlântico"],
  ["ACA-RD-07D", "Acaraú", "Parceira", "Atlântico"],
  ["ACA-RD-21B", "Acaraú", "Parceira", "Atlântico"],
  ["ACA-RD-21C", "Acaraú", "Parceira", "Atlântico"],
  ["ACA-RD-31B", "Acaraú", "Parceira", "Atlântico"],
  // Base: Itapajé
  ["ITE-RD-01B", "Itapajé", "Parceira", "Atlântico"],
  ["ITE-RD-01B1", "Itapajé", "Parceira", "Atlântico"],
  ["ITE-RD-01C", "Itapajé", "Parceira", "Atlântico"],
  ["ITE-RD-01C1", "Itapajé", "Parceira", "Atlântico"],
  ["ITE-RD-02B", "Itapajé", "Parceira", "Atlântico"],
  ["ITE-RD-02C", "Itapajé", "Parceira", "Atlântico"],
  ["ITE-RD-02C2", "Itapajé", "Parceira", "Atlântico"],
  ["ITE-RD-03B", "Itapajé", "Parceira", "Atlântico"],
  ["ITE-RD-03C", "Itapajé", "Parceira", "Atlântico"],
  ["ITE-RD-03C3", "Itapajé", "Parceira", "Atlântico"],
  ["ITE-TR-03B", "Itapajé", "Parceira", "Atlântico"],
  ["ITE-TR-03C", "Itapajé", "Parceira", "Atlântico"],
  // Base: Itapipoca
  ["IPK-RD-01B", "Itapipoca", "Parceira", "Atlântico"],
  ["IPK-RD-01C", "Itapipoca", "Parceira", "Atlântico"],
  ["IPK-RD-11B", "Itapipoca", "Parceira", "Atlântico"],
  ["IPK-RD-11B1", "Itapipoca", "Parceira", "Atlântico"],
  ["IPK-RD-12C", "Itapipoca", "Parceira", "Atlântico"],
  ["IPK-RD-12C1", "Itapipoca", "Parceira", "Atlântico"],
  ["IPK-RD-21B", "Itapipoca", "Parceira", "Atlântico"],
  ["IPK-RD-21C", "Itapipoca", "Parceira", "Atlântico"],
  ["IPK-SK-01B", "Itapipoca", "Parceira", "Atlântico"],
  ["IPK-SK-01C", "Itapipoca", "Parceira", "Atlântico"],
  ["IPK-SK-01C1", "Itapipoca", "Parceira", "Atlântico"],
  ["ITK-RD-10B", "Itapipoca", "Parceira", "Atlântico"],
  ["ITK-RD-31B", "Itapipoca", "Parceira", "Atlântico"],
  ["ITK-RD-32B", "Itapipoca", "Parceira", "Atlântico"],
  // Base: Trairi
  ["IPT-RD-01B", "Trairi", "Parceira", "Atlântico"],
  ["IPT-RD-02B", "Trairi", "Parceira", "Atlântico"],
  ["IPT-RD-02C", "Trairi", "Parceira", "Atlântico"],
  ["IPT-RD-03C", "Trairi", "Parceira", "Atlântico"],
  ["IPT-RD-21D", "Trairi", "Parceira", "Atlântico"],
  ["IPT-RD-23B", "Trairi", "Parceira", "Atlântico"],
  ["IPT-RD-31B", "Trairi", "Parceira", "Atlântico"],
  ["IPT-RD-32C", "Trairi", "Parceira", "Atlântico"],
  ["IPT-TR-02B", "Trairi", "Parceira", "Atlântico"],
  ["IPT-TR-02C", "Trairi", "Parceira", "Atlântico"],
  ["IPT-TR-31B", "Trairi", "Parceira", "Atlântico"],
  ["IPT-TR-32C", "Trairi", "Parceira", "Atlântico"],
  ["ITC-RD-01B", "Trairi", "Parceira", "Atlântico"],
  ["ITC-RD-01B1", "Trairi", "Parceira", "Atlântico"],
  ["ITC-RD-03C", "Trairi", "Parceira", "Atlântico"],
  ["ITC-RD-03C1", "Trairi", "Parceira", "Atlântico"],
  ["ITC-RD-21D", "Trairi", "Parceira", "Atlântico"],
  ["ITC-RD-21D1", "Trairi", "Parceira", "Atlântico"],
  ["ITC-RD-23B", "Trairi", "Parceira", "Atlântico"],
  ["ITC-RD-23B1", "Trairi", "Parceira", "Atlântico"],
  ["ITP-RD-01B", "Trairi", "Parceira", "Atlântico"],
  ["TRI-RD-01B", "Trairi", "Parceira", "Atlântico"],
  ["TRI-RD-03C", "Trairi", "Parceira", "Atlântico"],
  ["TRI-RD-21D", "Trairi", "Parceira", "Atlântico"],
  ["TRI-RD-23B", "Trairi", "Parceira", "Atlântico"],
  ["TRI-RD-31B", "Trairi", "Parceira", "Atlântico"],
  ["TRI-RD-32C", "Trairi", "Parceira", "Atlântico"],
  // Base: Itapipoca
  ["ICC-IN-01B", "Itapipoca", "Parceira", "Atlântico"],
  ["IPK-IN-03B", "Itapipoca", "Parceira", "Atlântico"],
  ["IPK-IN-04B", "Itapipoca", "Parceira", "Atlântico"],
  ["IPK-IN-05B", "Itapipoca", "Parceira", "Atlântico"],
  ["IPK-IN-06B", "Itapipoca", "Parceira", "Atlântico"],
  ["IPK-IN-07B", "Itapipoca", "Parceira", "Atlântico"],
  ["IPK-IN-08B", "Itapipoca", "Parceira", "Atlântico"],
  ["IPK-IN-09B", "Itapipoca", "Parceira", "Atlântico"],
  ["IPK-IN-10B", "Itapipoca", "Parceira", "Atlântico"],
  ["IPK-IN-11B", "Itapipoca", "Parceira", "Atlântico"],
  ["IPK-IN-12B", "Itapipoca", "Parceira", "Atlântico"],
  ["ITE-IN-02B", "Itapipoca", "Parceira", "Atlântico"],
  // Base: Acaraú
  ["ACU-AP-01B", "Acaraú", "Própria", "Atlântico"],
  ["ACU-AP-01D", "Acaraú", "Própria", "Atlântico"],
  ["ACU-LL-01B", "Acaraú", "Própria", "Atlântico"],
  ["ACU-ML-31B", "Acaraú", "Própria", "Atlântico"],
  ["ACU-MP-31B", "Acaraú", "Própria", "Atlântico"],
  ["ACU-MP-31D", "Acaraú", "Própria", "Atlântico"],
  ["ACU-PD-02B", "Acaraú", "Própria", "Atlântico"],
  ["ACU-PD-20B", "Acaraú", "Própria", "Atlântico"],
  ["ACU-PD-21B", "Acaraú", "Própria", "Atlântico"],
  ["ACU-PD-23B", "Acaraú", "Própria", "Atlântico"],
  ["ACU-RD-01B", "Acaraú", "Própria", "Atlântico"],
  ["ACU-RD-01C", "Acaraú", "Própria", "Atlântico"],
  ["ACU-RD-01D", "Acaraú", "Própria", "Atlântico"],
  ["ACU-RD-02B", "Acaraú", "Própria", "Atlântico"],
  ["ACU-RD-31B", "Acaraú", "Própria", "Atlântico"],
  ["ACU-RD-31C", "Acaraú", "Própria", "Atlântico"],
  ["ACU-RD-31D", "Acaraú", "Própria", "Atlântico"],
  ["ACU-RL-01D", "Acaraú", "Própria", "Atlântico"],
  ["ACU-SG-01C", "Acaraú", "Própria", "Atlântico"],
  ["ACU-SG-01D", "Acaraú", "Própria", "Atlântico"],
  ["ACU-SG-31B", "Acaraú", "Própria", "Atlântico"],
  ["ACU-SG-31D", "Acaraú", "Própria", "Atlântico"],
  ["ACU-SP-01C", "Acaraú", "Própria", "Atlântico"],
  ["ACU-TR-01B", "Acaraú", "Própria", "Atlântico"],
  ["ACU-TR-01D", "Acaraú", "Própria", "Atlântico"],
  ["ACU-TR-02B", "Acaraú", "Própria", "Atlântico"],
  ["ACU-TR-02D", "Acaraú", "Própria", "Atlântico"],
  ["ACU-TR-03B", "Acaraú", "Própria", "Atlântico"],
  // Base: Itapajé
  ["ITJ-LL-15B", "Itapajé", "Própria", "Atlântico"],
  ["ITJ-PD-11B", "Itapajé", "Própria", "Atlântico"],
  ["ITJ-PD-20B", "Itapajé", "Própria", "Atlântico"],
  ["ITJ-PD-22C", "Itapajé", "Própria", "Atlântico"],
  ["ITJ-RD-04D", "Itapajé", "Própria", "Atlântico"],
  ["ITJ-RD-05B", "Itapajé", "Própria", "Atlântico"],
  ["ITJ-SG-07B", "Itapajé", "Própria", "Atlântico"],
  ["ITJ-SP-01B", "Itapajé", "Própria", "Atlântico"],
  ["ITJ-TR-02D", "Itapajé", "Própria", "Atlântico"],
  ["ITJ-TR-03B", "Itapajé", "Própria", "Atlântico"],
  // Base: Itapipoca
  ["IPK-EN-90B", "Itapipoca", "Própria", "Atlântico"],
  ["IPK-EN-91B", "Itapipoca", "Própria", "Atlântico"],
  ["IPT-EN-91B", "Itapipoca", "Própria", "Atlântico"],
  ["ITK-ML-31B", "Itapipoca", "Própria", "Atlântico"],
  ["ITK-ML-32B", "Itapipoca", "Própria", "Atlântico"],
  ["ITK-MP-30B", "Itapipoca", "Própria", "Atlântico"],
  ["ITK-MP-30D", "Itapipoca", "Própria", "Atlântico"],
  ["ITK-MP-33B", "Itapipoca", "Própria", "Atlântico"],
  ["ITK-PD-01B", "Itapipoca", "Própria", "Atlântico"],
  ["ITK-PD-03B", "Itapipoca", "Própria", "Atlântico"],
  ["ITK-PD-04B", "Itapipoca", "Própria", "Atlântico"],
  ["ITK-PD-20B", "Itapipoca", "Própria", "Atlântico"],
  ["ITK-PD-21C", "Itapipoca", "Própria", "Atlântico"],
  ["ITK-RD-06C", "Itapipoca", "Própria", "Atlântico"],
  ["ITK-SG-01B", "Itapipoca", "Própria", "Atlântico"],
  ["ITK-SG-07C", "Itapipoca", "Própria", "Atlântico"],
  ["ITK-SP-05D", "Itapipoca", "Própria", "Atlântico"],
  ["ITK-TR-02B", "Itapipoca", "Própria", "Atlântico"],
  ["ITK-TR-04D", "Itapipoca", "Própria", "Atlântico"],
  // Base: Trairi
  ["TRR-LC-07B", "Trairi", "Própria", "Atlântico"],
  ["TRR-LL-06B", "Trairi", "Própria", "Atlântico"],
  ["TRR-PD-05B", "Trairi", "Própria", "Atlântico"],
  ["TRR-PD-21C", "Trairi", "Própria", "Atlântico"],
  ["TRR-PD-22B", "Trairi", "Própria", "Atlântico"],
  ["TRR-RD-01B", "Trairi", "Própria", "Atlântico"],
  ["TRR-RD-01D", "Trairi", "Própria", "Atlântico"],
  ["TRR-RD-02D", "Trairi", "Própria", "Atlântico"],
  ["TRR-RD-04D", "Trairi", "Própria", "Atlântico"],
  ["TRR-SG-01B", "Trairi", "Própria", "Atlântico"],
  ["TRR-SP-02D", "Trairi", "Própria", "Atlântico"],
  ["TRR-TR-03C", "Trairi", "Própria", "Atlântico"],
  ["TRR-TR-04D", "Trairi", "Própria", "Atlântico"],
  // Norte: 232 equipes
  // Base: Sobral
  ["SBA-LN-01B", "Sobral", "Parceira", "Norte"],
  ["SBA-LN-06B", "Sobral", "Parceira", "Norte"],
  ["SBA-LN-09B", "Sobral", "Parceira", "Norte"],
  ["SBA-RD-01B", "Sobral", "Parceira", "Norte"],
  ["SBA-RD-02B", "Sobral", "Parceira", "Norte"],
  // Base: Camocim
  ["CMK-CR-02B", "Camocim", "Parceira", "Norte"],
  ["CMK-LN-04B", "Camocim", "Parceira", "Norte"],
  ["CMK-NO-06B", "Camocim", "Parceira", "Norte"],
  ["CMK-RD-01D", "Camocim", "Parceira", "Norte"],
  ["CMK-RD-02C", "Camocim", "Parceira", "Norte"],
  ["CMK-RD-04B", "Camocim", "Parceira", "Norte"],
  // Base: Inhuçu
  ["STB-CO-05B", "Inhuçu", "Parceira", "Norte"],
  ["STB-LM-03B", "Inhuçu", "Parceira", "Norte"],
  ["STB-LM-04B", "Inhuçu", "Parceira", "Norte"],
  ["STB-NO-05C", "Inhuçu", "Parceira", "Norte"],
  ["STB-RD-10B", "Inhuçu", "Parceira", "Norte"],
  ["STB-RD-11B", "Inhuçu", "Parceira", "Norte"],
  ["STB-RD-11C", "Inhuçu", "Parceira", "Norte"],
  // Base: Sobral
  ["SBC-RD-31B", "Sobral", "Parceira", "Norte"],
  ["SBM-RD-12C", "Sobral", "Parceira", "Norte"],
  ["SBR-RD-04C", "Sobral", "Parceira", "Norte"],
  ["SBU-LN-01B", "Sobral", "Parceira", "Norte"],
  ["SBU-LN-02B", "Sobral", "Parceira", "Norte"],
  ["SBU-LN-04B", "Sobral", "Parceira", "Norte"],
  ["SBU-LN-05B", "Sobral", "Parceira", "Norte"],
  ["SBU-LN-07B", "Sobral", "Parceira", "Norte"],
  ["SBU-LN-08B", "Sobral", "Parceira", "Norte"],
  ["SBU-MP-01B", "Sobral", "Parceira", "Norte"],
  ["SBU-RD-22C", "Sobral", "Parceira", "Norte"],
  ["SBU-RD-51B", "Sobral", "Parceira", "Norte"],
  ["SBU-RD-52C", "Sobral", "Parceira", "Norte"],
  ["SBU-RD-62C", "Sobral", "Parceira", "Norte"],
  // Base: Tianguá
  ["STM-RD-70B", "Tianguá", "Parceira", "Norte"],
  ["STM-RD-71B", "Tianguá", "Parceira", "Norte"],
  ["STM-RD-71C", "Tianguá", "Parceira", "Norte"],
  ["STT-RD-30B", "Tianguá", "Parceira", "Norte"],
  ["STT-RD-31C", "Tianguá", "Parceira", "Norte"],
  ["STT-RD-40B", "Tianguá", "Parceira", "Norte"],
  ["STT-RD-41B", "Tianguá", "Parceira", "Norte"],
  ["STT-RD-41C", "Tianguá", "Parceira", "Norte"],
  ["STV-CO-01B", "Tianguá", "Parceira", "Norte"],
  ["STV-RD-30B", "Tianguá", "Parceira", "Norte"],
  ["STV-RD-30C", "Tianguá", "Parceira", "Norte"],
  ["STV-RD-31C", "Tianguá", "Parceira", "Norte"],
  // Base: Sobral
  ["SBU-IN-31B", "Sobral", "Parceira", "Norte"],
  ["SBU-IN-34B", "Sobral", "Parceira", "Norte"],
  ["SBU-IN-35B", "Sobral", "Parceira", "Norte"],
  ["SBU-IN-36B", "Sobral", "Parceira", "Norte"],
  ["SBU-IN-37B", "Sobral", "Parceira", "Norte"],
  ["SBU-IN-38B", "Sobral", "Parceira", "Norte"],
  ["SBU-IN-43B", "Sobral", "Parceira", "Norte"],
  ["SBU-IN-44B", "Sobral", "Parceira", "Norte"],
  // Base: Tianguá
  ["STI-IN-32B", "Tianguá", "Parceira", "Norte"],
  ["STI-IN-33B", "Tianguá", "Parceira", "Norte"],
  ["STI-IN-48B", "Tianguá", "Parceira", "Norte"],
  ["STT-IN-42B", "Tianguá", "Parceira", "Norte"],
  // Base: Camocim
  ["CMC-EM-01D", "Camocim", "Própria", "Norte"],
  ["CMC-EM-02B", "Camocim", "Própria", "Norte"],
  ["CMC-EM-03C", "Camocim", "Própria", "Norte"],
  ["CMC-EM-03D", "Camocim", "Própria", "Norte"],
  ["CMC-EM-31B", "Camocim", "Própria", "Norte"],
  ["CMC-EP-01B", "Camocim", "Própria", "Norte"],
  ["CMC-IE-01B", "Camocim", "Própria", "Norte"],
  ["CMC-IE-02B", "Camocim", "Própria", "Norte"],
  ["CMC-LC-31B", "Camocim", "Própria", "Norte"],
  ["CMC-LL-01B", "Camocim", "Própria", "Norte"],
  ["CMC-LV-31B", "Camocim", "Própria", "Norte"],
  ["CMC-ML-31B", "Camocim", "Própria", "Norte"],
  ["CMC-MP-31B", "Camocim", "Própria", "Norte"],
  ["CMC-PD-31B", "Camocim", "Própria", "Norte"],
  ["CMC-PD-32B", "Camocim", "Própria", "Norte"],
  ["CMC-PD-33B", "Camocim", "Própria", "Norte"],
  ["CMC-RD-01D", "Camocim", "Própria", "Norte"],
  ["CMC-RD-05B", "Camocim", "Própria", "Norte"],
  ["CMC-RE-92B", "Camocim", "Própria", "Norte"],
  ["CMC-RE-93B", "Camocim", "Própria", "Norte"],
  ["CMC-RE-95B", "Camocim", "Própria", "Norte"],
  ["CMC-RT-91B", "Camocim", "Própria", "Norte"],
  ["CMC-RT-92B", "Camocim", "Própria", "Norte"],
  ["CMC-RT-93B", "Camocim", "Própria", "Norte"],
  ["CMC-RT-94B", "Camocim", "Própria", "Norte"],
  ["CMC-RT-95B", "Camocim", "Própria", "Norte"],
  ["CMC-SG-02B", "Camocim", "Própria", "Norte"],
  ["CMC-SG-02C", "Camocim", "Própria", "Norte"],
  ["CMC-SG-04B", "Camocim", "Própria", "Norte"],
  ["CMC-SG-04C", "Camocim", "Própria", "Norte"],
  ["CMC-SG-31B", "Camocim", "Própria", "Norte"],
  ["CMC-SP-01C", "Camocim", "Própria", "Norte"],
  ["CMC-TR-01B", "Camocim", "Própria", "Norte"],
  ["CMC-TR-03D", "Camocim", "Própria", "Norte"],
  ["CMK-RD-01B", "Camocim", "Própria", "Norte"],
  // Base: Inhuçu
  ["INH-EM-31B", "Inhuçu", "Própria", "Norte"],
  ["INH-EM-32B", "Inhuçu", "Própria", "Norte"],
  ["INH-EP-01B", "Inhuçu", "Própria", "Norte"],
  ["INH-LC-31B", "Inhuçu", "Própria", "Norte"],
  ["INH-ML-02B", "Inhuçu", "Própria", "Norte"],
  ["INH-ML-10B", "Inhuçu", "Própria", "Norte"],
  ["INH-ML-31B", "Inhuçu", "Própria", "Norte"],
  ["INH-ML-32B", "Inhuçu", "Própria", "Norte"],
  ["INH-MP-01B", "Inhuçu", "Própria", "Norte"],
  ["INH-PD-01B", "Inhuçu", "Própria", "Norte"],
  ["INH-PD-02B", "Inhuçu", "Própria", "Norte"],
  ["INH-PD-08B", "Inhuçu", "Própria", "Norte"],
  ["INH-PD-30B", "Inhuçu", "Própria", "Norte"],
  ["INH-RD-02B", "Inhuçu", "Própria", "Norte"],
  ["INH-RD-04B", "Inhuçu", "Própria", "Norte"],
  ["INH-RD-05C", "Inhuçu", "Própria", "Norte"],
  ["INH-RD-06B", "Inhuçu", "Própria", "Norte"],
  ["INH-RD-07D", "Inhuçu", "Própria", "Norte"],
  ["INH-RD-08B", "Inhuçu", "Própria", "Norte"],
  ["INH-RD-10B", "Inhuçu", "Própria", "Norte"],
  ["INH-RD-30B", "Inhuçu", "Própria", "Norte"],
  ["INH-RD-31B", "Inhuçu", "Própria", "Norte"],
  ["INH-RD-32B", "Inhuçu", "Própria", "Norte"],
  ["INH-RE-93B", "Inhuçu", "Própria", "Norte"],
  ["INH-RT-93B", "Inhuçu", "Própria", "Norte"],
  ["INH-SG-02B", "Inhuçu", "Própria", "Norte"],
  ["INH-SG-08C", "Inhuçu", "Própria", "Norte"],
  ["INH-SG-31B", "Inhuçu", "Própria", "Norte"],
  ["INH-SG-32B", "Inhuçu", "Própria", "Norte"],
  ["INH-SP-03B", "Inhuçu", "Própria", "Norte"],
  ["INH-SP-08D", "Inhuçu", "Própria", "Norte"],
  ["INH-TR-02B", "Inhuçu", "Própria", "Norte"],
  ["INH-TR-04B", "Inhuçu", "Própria", "Norte"],
  ["INH-TR-07D", "Inhuçu", "Própria", "Norte"],
  ["STB-EN-90B", "Inhuçu", "Própria", "Norte"],
  ["STB-EN-91B", "Inhuçu", "Própria", "Norte"],
  ["STB-EN-92B", "Inhuçu", "Própria", "Norte"],
  ["STB-EN-93B", "Inhuçu", "Própria", "Norte"],
  ["STB-EN-94B", "Inhuçu", "Própria", "Norte"],
  ["STB-EN-95B", "Inhuçu", "Própria", "Norte"],
  ["STB-RD-01B", "Inhuçu", "Própria", "Norte"],
  ["STB-RD-02C", "Inhuçu", "Própria", "Norte"],
  // Base: Sobral
  ["SBC-RD-21B", "Sobral", "Própria", "Norte"],
  ["SBF-RD-31B", "Sobral", "Própria", "Norte"],
  ["SBL-EM-31B", "Sobral", "Própria", "Norte"],
  ["SBL-EP-01B", "Sobral", "Própria", "Norte"],
  ["SBL-EP-02D", "Sobral", "Própria", "Norte"],
  ["SBL-EP-31B", "Sobral", "Própria", "Norte"],
  ["SBL-IE-01B", "Sobral", "Própria", "Norte"],
  ["SBL-LC-31B", "Sobral", "Própria", "Norte"],
  ["SBL-LL-01B", "Sobral", "Própria", "Norte"],
  ["SBL-LL-02B", "Sobral", "Própria", "Norte"],
  ["SBL-LL-03B", "Sobral", "Própria", "Norte"],
  ["SBL-ML-32B", "Sobral", "Própria", "Norte"],
  ["SBL-MP-01B", "Sobral", "Própria", "Norte"],
  ["SBL-MP-02D", "Sobral", "Própria", "Norte"],
  ["SBL-MP-31B", "Sobral", "Própria", "Norte"],
  ["SBL-MP-32B", "Sobral", "Própria", "Norte"],
  ["SBL-PD-01B", "Sobral", "Própria", "Norte"],
  ["SBL-PD-01D", "Sobral", "Própria", "Norte"],
  ["SBL-PD-02B", "Sobral", "Própria", "Norte"],
  ["SBL-PD-03B", "Sobral", "Própria", "Norte"],
  ["SBL-PD-04B", "Sobral", "Própria", "Norte"],
  ["SBL-PD-05B", "Sobral", "Própria", "Norte"],
  ["SBL-PD-05C", "Sobral", "Própria", "Norte"],
  ["SBL-PD-06B", "Sobral", "Própria", "Norte"],
  ["SBL-PD-07B", "Sobral", "Própria", "Norte"],
  ["SBL-RD-01B", "Sobral", "Própria", "Norte"],
  ["SBL-RD-02B", "Sobral", "Própria", "Norte"],
  ["SBL-RD-03B", "Sobral", "Própria", "Norte"],
  ["SBL-RD-03C", "Sobral", "Própria", "Norte"],
  ["SBL-RD-04B", "Sobral", "Própria", "Norte"],
  ["SBL-RD-04C", "Sobral", "Própria", "Norte"],
  ["SBL-RD-05C", "Sobral", "Própria", "Norte"],
  ["SBL-RD-05D", "Sobral", "Própria", "Norte"],
  ["SBL-RD-06B", "Sobral", "Própria", "Norte"],
  ["SBL-RD-06D", "Sobral", "Própria", "Norte"],
  ["SBL-RD-07D", "Sobral", "Própria", "Norte"],
  ["SBL-RD-08B", "Sobral", "Própria", "Norte"],
  ["SBL-RD-08D", "Sobral", "Própria", "Norte"],
  ["SBL-RD-09D", "Sobral", "Própria", "Norte"],
  ["SBL-SG-03B", "Sobral", "Própria", "Norte"],
  ["SBL-SG-04B", "Sobral", "Própria", "Norte"],
  ["SBL-SG-06C", "Sobral", "Própria", "Norte"],
  ["SBL-SG-31B", "Sobral", "Própria", "Norte"],
  ["SBL-SG-32B", "Sobral", "Própria", "Norte"],
  ["SBR-RD-03B", "Sobral", "Própria", "Norte"],
  ["SBR-RD-05C", "Sobral", "Própria", "Norte"],
  ["SBU-EN-90B", "Sobral", "Própria", "Norte"],
  ["SBU-EN-91B", "Sobral", "Própria", "Norte"],
  ["SBU-EN-93B", "Sobral", "Própria", "Norte"],
  ["SBU-EN-94B", "Sobral", "Própria", "Norte"],
  ["SBU-EN-95B", "Sobral", "Própria", "Norte"],
  ["SBU-EN-96B", "Sobral", "Própria", "Norte"],
  ["SBU-EN-98B", "Sobral", "Própria", "Norte"],
  ["SBU-EN-99B", "Sobral", "Própria", "Norte"],
  ["SBU-RD-21B", "Sobral", "Própria", "Norte"],
  ["SBU-RE-90B", "Sobral", "Própria", "Norte"],
  ["SBU-RE-93B", "Sobral", "Própria", "Norte"],
  ["SBU-RE-94B", "Sobral", "Própria", "Norte"],
  ["SBU-RE-96B", "Sobral", "Própria", "Norte"],
  // Base: Tianguá
  ["STM-RD-61B", "Tianguá", "Própria", "Norte"],
  ["STM-RD-62C", "Tianguá", "Própria", "Norte"],
  ["STT-EN-91B", "Tianguá", "Própria", "Norte"],
  ["STT-EN-92B", "Tianguá", "Própria", "Norte"],
  ["STT-EN-93B", "Tianguá", "Própria", "Norte"],
  ["STT-EN-94B", "Tianguá", "Própria", "Norte"],
  ["STT-RD-31B", "Tianguá", "Própria", "Norte"],
  ["STT-RD-33B", "Tianguá", "Própria", "Norte"],
  ["STV-EN-91D", "Tianguá", "Própria", "Norte"],
  ["STV-RD-21B", "Tianguá", "Própria", "Norte"],
  ["STV-RD-22C", "Tianguá", "Própria", "Norte"],
  ["TNG-EM-01B", "Tianguá", "Própria", "Norte"],
  ["TNG-EM-31B", "Tianguá", "Própria", "Norte"],
  ["TNG-EP-30B", "Tianguá", "Própria", "Norte"],
  ["TNG-EP-32D", "Tianguá", "Própria", "Norte"],
  ["TNG-LL-08B", "Tianguá", "Própria", "Norte"],
  ["TNG-ML-01B", "Tianguá", "Própria", "Norte"],
  ["TNG-ML-03B", "Tianguá", "Própria", "Norte"],
  ["TNG-ML-05B", "Tianguá", "Própria", "Norte"],
  ["TNG-ML-32B", "Tianguá", "Própria", "Norte"],
  ["TNG-MP-30B", "Tianguá", "Própria", "Norte"],
  ["TNG-MP-32D", "Tianguá", "Própria", "Norte"],
  ["TNG-PD-05B", "Tianguá", "Própria", "Norte"],
  ["TNG-PD-06B", "Tianguá", "Própria", "Norte"],
  ["TNG-PD-07B", "Tianguá", "Própria", "Norte"],
  ["TNG-PD-08B", "Tianguá", "Própria", "Norte"],
  ["TNG-RD-01C", "Tianguá", "Própria", "Norte"],
  ["TNG-RD-03B", "Tianguá", "Própria", "Norte"],
  ["TNG-RD-06B", "Tianguá", "Própria", "Norte"],
  ["TNG-RD-07D", "Tianguá", "Própria", "Norte"],
  ["TNG-RD-31D", "Tianguá", "Própria", "Norte"],
  ["TNG-RE-91B", "Tianguá", "Própria", "Norte"],
  ["TNG-RT-91B", "Tianguá", "Própria", "Norte"],
  ["TNG-RT-91D", "Tianguá", "Própria", "Norte"],
  ["TNG-RT-92B", "Tianguá", "Própria", "Norte"],
  ["TNG-RT-93B", "Tianguá", "Própria", "Norte"],
  ["TNG-RT-94B", "Tianguá", "Própria", "Norte"],
  ["TNG-SG-32B", "Tianguá", "Própria", "Norte"],
  ["TNG-SP-04C", "Tianguá", "Própria", "Norte"],
  ["TNG-TR-01B", "Tianguá", "Própria", "Norte"],
  // Centro-Norte: 77 equipes
  // Base: Canindé
  ["CNB-EN-90B", "Canindé", "Própria", "Centro-Norte"],
  ["CNI-RD-21B", "Canindé", "Parceira", "Centro-Norte"],
  ["CNB-EN-91B", "Canindé", "Própria", "Centro-Norte"],
  ["CND-RD-21B", "Canindé", "Parceira", "Centro-Norte"],
  ["CNB-EN-92B", "Canindé", "Própria", "Centro-Norte"],
  ["CNI-RD-21C", "Canindé", "Parceira", "Centro-Norte"],
  ["CND-EN-90B", "Canindé", "Própria", "Centro-Norte"],
  ["CND-RD-21D", "Canindé", "Parceira", "Centro-Norte"],
  ["CND-EN-91B", "Canindé", "Própria", "Centro-Norte"],
  ["CND-RD-22B", "Canindé", "Parceira", "Centro-Norte"],
  ["CND-EN-92B", "Canindé", "Própria", "Centro-Norte"],
  ["CND-RD-23B", "Canindé", "Parceira", "Centro-Norte"],
  ["CND-EN-93B", "Canindé", "Própria", "Centro-Norte"],
  ["CND-RD-21C", "Canindé", "Parceira", "Centro-Norte"],
  ["CND-EN-94B", "Canindé", "Própria", "Centro-Norte"],
  ["CNB-RD-21C", "Canindé", "Parceira", "Centro-Norte"],
  ["CND-EN-95B", "Canindé", "Própria", "Centro-Norte"],
  ["CNM-RD-21D", "Canindé", "Parceira", "Centro-Norte"],
  ["CNM-RD-21B", "Canindé", "Parceira", "Centro-Norte"],
  ["CNB-RD-21B", "Canindé", "Parceira", "Centro-Norte"],
  // Base: Quixadá
  ["CNQ-EN-90B", "Quixadá", "Própria", "Centro-Norte"],
  ["QXD-RD-21B", "Quixadá", "Parceira", "Centro-Norte"],
  ["CNQ-EN-91B", "Quixadá", "Própria", "Centro-Norte"],
  ["QXD-RD-22B", "Quixadá", "Parceira", "Centro-Norte"],
  ["CNQ-EN-92B", "Quixadá", "Própria", "Centro-Norte"],
  ["QXD-RD-21C", "Quixadá", "Parceira", "Centro-Norte"],
  ["CNQ-EN-93B", "Quixadá", "Própria", "Centro-Norte"],
  ["QXD-RD-21D", "Quixadá", "Parceira", "Centro-Norte"],
  ["CNQ-EN-94B", "Quixadá", "Própria", "Centro-Norte"],
  ["QXU-RD-21B", "Quixadá", "Parceira", "Centro-Norte"],
  ["CNX-EN-90B", "Quixadá", "Própria", "Centro-Norte"],
  ["QXU-RD-21D", "Quixadá", "Parceira", "Centro-Norte"],
  ["CNX-EN-91B", "Quixadá", "Própria", "Centro-Norte"],
  ["QXB-RD-21B", "Quixadá", "Parceira", "Centro-Norte"],
  ["CNX-EN-92B", "Quixadá", "Própria", "Centro-Norte"],
  ["QXB-RD-22B", "Quixadá", "Parceira", "Centro-Norte"],
  ["CNX-EN-94B", "Quixadá", "Própria", "Centro-Norte"],
  ["QXB-RD-21D", "Quixadá", "Parceira", "Centro-Norte"],
  ["QXB-RD-21C", "Quixadá", "Parceira", "Centro-Norte"],
  ["QXD-RD-23B", "Quixadá", "Parceira", "Centro-Norte"],
  // Base: Crateús
  ["NVC-EN-90B", "Crateús", "Própria", "Centro-Norte"],
  ["CAT-RD-21B", "Crateús", "Parceira", "Centro-Norte"],
  ["NVC-EN-91B", "Crateús", "Própria", "Centro-Norte"],
  ["NVC-EN-92B", "Crateús", "Própria", "Centro-Norte"],
  ["CAT-RD-21C", "Crateús", "Parceira", "Centro-Norte"],
  ["NVC-EN-93B", "Crateús", "Própria", "Centro-Norte"],
  ["CAT-RD-22C", "Crateús", "Parceira", "Centro-Norte"],
  ["NVC-EN-94B", "Crateús", "Própria", "Centro-Norte"],
  ["CAT-RD-23C", "Crateús", "Parceira", "Centro-Norte"],
  ["NVC-EN-95B", "Crateús", "Própria", "Centro-Norte"],
  ["CAT-RD-21D", "Crateús", "Parceira", "Centro-Norte"],
  // Base: Nova Russas
  ["NVQ-EN-90B", "Nova Russas", "Própria", "Centro-Norte"],
  ["NVM-RD-21B", "Nova Russas", "Parceira", "Centro-Norte"],
  ["NVQ-EN-91B", "Nova Russas", "Própria", "Centro-Norte"],
  ["NVR-RD-21D", "Nova Russas", "Parceira", "Centro-Norte"],
  ["NVQ-EN-92B", "Nova Russas", "Própria", "Centro-Norte"],
  ["NVR-RD-21B", "Nova Russas", "Parceira", "Centro-Norte"],
  ["NVQ-EN-93B", "Nova Russas", "Própria", "Centro-Norte"],
  ["NVI-RD-21B", "Nova Russas", "Parceira", "Centro-Norte"],
  ["NVR-EN-90B", "Nova Russas", "Própria", "Centro-Norte"],
  ["NVQ-RD-21B", "Nova Russas", "Parceira", "Centro-Norte"],
  ["NVR-EN-91B", "Nova Russas", "Própria", "Centro-Norte"],
  ["NVV-RD-21B", "Nova Russas", "Parceira", "Centro-Norte"],
  ["NVR-EN-92B", "Nova Russas", "Própria", "Centro-Norte"],
  ["NVR-RD-22C", "Nova Russas", "Parceira", "Centro-Norte"],
  ["NVR-EN-93B", "Nova Russas", "Própria", "Centro-Norte"],
  ["NVI-RD-21C", "Nova Russas", "Parceira", "Centro-Norte"],
  ["NVR-EN-94B", "Nova Russas", "Própria", "Centro-Norte"],
  ["NVV-RD-21C", "Nova Russas", "Parceira", "Centro-Norte"],
  ["NVR-EN-95B", "Nova Russas", "Própria", "Centro-Norte"],
  ["NVQ-RD-21D", "Nova Russas", "Parceira", "Centro-Norte"],
  ["NVV-EN-90B", "Nova Russas", "Própria", "Centro-Norte"],
  ["NVR-RD-23B", "Nova Russas", "Parceira", "Centro-Norte"],
  ["NVR-RD-21C", "Nova Russas", "Parceira", "Centro-Norte"],
  ["NVR-RD-22B", "Nova Russas", "Parceira", "Centro-Norte"],
  ["NVI-RD-22B", "Nova Russas", "Parceira", "Centro-Norte"],
  ["NVV-RD-22B", "Nova Russas", "Parceira", "Centro-Norte"],
];

const catalogByTeam = new Map();

for (const [equipe, base, tipoEquipe, polo] of RAW_TEAM_CATALOG) {
  const code = String(equipe || '').trim();
  const key = normalizeToken(code);
  if (!key) continue;

  const entry = Object.freeze({
    equipe: code,
    base: canonicalBase(base),
    periodo: resolveTeamPeriod(code),
    tipoEquipe: canonicalTeamType(tipoEquipe),
    polo: canonicalPolo(polo)
  });

  const current = catalogByTeam.get(key);
  if (current && !sameMetadata(current, entry)) {
    throw new Error(`Conflito no catálogo da equipe ${code}.`);
  }
  catalogByTeam.set(key, entry);
}

export const VTR_TEAM_CATALOG = Object.freeze([...catalogByTeam.values()]);

export const VTR_TEAM_INDEX = new Map(
  VTR_TEAM_CATALOG.map((entry) => [normalizeToken(entry.equipe), entry])
);

// B = Manhã, C = Tarde e D = Noite.
// Alguns códigos da planilha terminam em B1, C1, C2, C3 ou D1;
// nesses casos, a letra imediatamente anterior aos dígitos define o período.
export function resolveTeamPeriod(teamName, fallback = '') {
  const code = String(teamName || '').trim().toUpperCase();
  const match = code.match(/([BCD])\d*$/);
  return match ? PERIOD_BY_SUFFIX[match[1]] : String(fallback || '').trim();
}

export function canonicalBase(base) {
  const value = String(base || '').trim();
  return BASE_BY_TOKEN.get(normalizeToken(value)) || value;
}

function canonicalPolo(polo) {
  const value = String(polo || '').trim();
  return POLO_BY_TOKEN.get(normalizeToken(value)) || value;
}

function canonicalTeamType(type) {
  const value = String(type || '').trim();
  return TEAM_TYPE_BY_TOKEN.get(normalizeToken(value)) || value;
}

function sameMetadata(a, b) {
  return a.base === b.base
    && a.periodo === b.periodo
    && a.tipoEquipe === b.tipoEquipe
    && a.polo === b.polo;
}
